### PR TITLE
added index.html

### PR DESCRIPTION
**Pull request by thetechtakeover**
Created the index.html file

### CODE REVIEW

**Review by nellarro — CHANGES_REQUESTED** [review]
🔧 Looks like we are missing the CSS file being included here.

**Comment by thetechtakeover** [comment]
Im not sure if I delete this pull request or not. I sent another one

**Comment by nellarro** [comment]
@thetechtakeover you should close this PR and reference the one that you want to use. I'll go ahead and do that for ya!

It's also ok to fix the PR instead of creating a new one. That will usually save you some time and effort.

**Comment by thetechtakeover** [comment]
I tried to fix it 100xs but no luck. When I tried to Fork the repo with the CSS file, the one I modified continued to show up only So i created a new one! :(

**Comment by thetechtakeover** [comment]
starting new request

**Comment by thetechtakeover** [comment]
Starting from ground Zero

**Pull request closed without merging**
